shamefullyHoist: true
sideEffectsCache: false
linkWorkspacePackages: true
saveWorkspaceProtocol: false
packages:
  - "packages/*"
onlyBuiltDependencies:
  - "@cloud-ru/ft-config-husky"
ignoredBuiltDependencies:
  - "unrs-resolver"
