import {
  COLORS,
  COLORS_ATTENTION,
  COLORS_AVATAR,
  COLORS_BRAND,
  COLORS_BREADCRUMBS,
  COLORS_BUTTON,
  COLORS_CHECKBOX,
  COLORS_DIVIDER,
  COLORS_DRAWER,
  COLORS_FORM_FIELD,
  COLORS_FORM_GROUP,
  COLORS_GENERAL,
  COLORS_HIERARCHY_MENU,
  COLORS_ICON_BUTTON,
  COLORS_INPUT,
  COLORS_LOGS_VIEW,
  COLORS_MODAL,
  COLORS_PAGINATE,
  COLORS_PRESET,
  COLORS_RADIO,
  COLORS_SELECT,
  COLORS_SLIDER,
  COLORS_SPIN,
  COLORS_STATUS,
  COLORS_SWITCH,
  COLORS_TABLE,
  COLORS_TABS,
  COLORS_TAG,
  COLORS_TOAST,
  COLORS_TOOLBAR,
  COLORS_TOOLTIP,
  COLORS_TYPOGRAPHY,
} from './vars';

export const greenDarkDeprecated = `
  ${COLORS_BRAND.GREEN}: #07E897;
  ${COLORS_BRAND.GREEN_GRADIENT}: linear-gradient(235.56deg, #07E897 40.45%, #00956F 90.43%);
  ${COLORS_BRAND.BLACK}: #343F48;
  ${COLORS_BRAND.GRAY}: #D2D2D2;

  ${COLORS.GRAY_1}: #C6C6C6;
  ${COLORS.GRAY_2}: #989EA3;
  ${COLORS.GRAY_3}: #858A8F;
  ${COLORS.GRAY_4}: #636773;
  ${COLORS.GRAY_5}: #45474D;
  ${COLORS.GRAY_6}: #454545;
  ${COLORS.GRAY_7}: #3C3D41;
  ${COLORS.GRAY_8}: #323538;
  ${COLORS.GRAY_9}: #272829;
  ${COLORS.GRAY_10}: #252525;
  ${COLORS.GRAY_11}: #171717;
  ${COLORS.WHITE}: #ffffff;
  ${COLORS.GREEN_1}: #67FBC6;
  ${COLORS.GREEN_2}: #00EA95;
  ${COLORS.GREEN_3}: #07E897;
  ${COLORS.GREEN_4}: #07D88D;
  ${COLORS.GREEN_5}: #07CC85;
  ${COLORS.GREEN_6}: #12BBA6;
  ${COLORS.GREEN_7}: #157552;
  ${COLORS.BLUE_1}: #258CB8;
  ${COLORS.BLUE_2}: #375EC9;
  ${COLORS.PURPLE}: #5C00EC;
  ${COLORS.RED_1}: #E84E58;
  ${COLORS.RED_2}: #FF0000;
  ${COLORS.YELLOW}: #F0D559;

  ${COLORS_PRESET.RED}: #98605B;
  ${COLORS_PRESET.PINK}: #8A5273;
  ${COLORS_PRESET.PURPLE}: #6A5B8C;
  ${COLORS_PRESET.BLUE}: #517086;
  ${COLORS_PRESET.GREEN}: #527771;
  ${COLORS_PRESET.YELLOW}: #9E9056;
  ${COLORS_PRESET.ORANGE}: #9A754F;
  ${COLORS_PRESET.BROWN}: #685C56;
  ${COLORS_PRESET.GRAY_DEFAULT}: #6C6F71;
  ${COLORS_PRESET.GRAY}: #515558;

  ${COLORS_TAG.RED}: #98605B;
  ${COLORS_TAG.PINK}: #8A5273;
  ${COLORS_TAG.PURPLE}: #6A5B8C;
  ${COLORS_TAG.BLUE}: #517086;
  ${COLORS_TAG.GREEN}: #527771;
  ${COLORS_TAG.YELLOW}: #9E9056;
  ${COLORS_TAG.ORANGE}: #9A754F;
  ${COLORS_TAG.BROWN}: #685C56;
  ${COLORS_TAG.GRAY_1}: #6C6F71;
  ${COLORS_TAG.GRAY_2}: #515558;
  ${COLORS_TAG.TAG_TEXT_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TAG.TAG_BG_GREEN}: var(${COLORS_PRESET.GREEN});
  ${COLORS_TAG.TAG_BG_BLUE}: var(${COLORS_PRESET.BLUE});
  ${COLORS_TAG.TAG_BG_PURPLE}: var(${COLORS_PRESET.PURPLE});
  ${COLORS_TAG.TAG_BG_PINK}: var(${COLORS_PRESET.PINK});
  ${COLORS_TAG.TAG_BG_RED}: var(${COLORS_PRESET.RED});
  ${COLORS_TAG.TAG_BG_GRAY_DEFAULT}: var(${COLORS_PRESET.GRAY_DEFAULT});
  ${COLORS_TAG.TAG_BG_GRAY}: var(${COLORS_PRESET.GRAY});
  ${COLORS_TAG.TAG_BG_BROWN}: var(${COLORS_PRESET.BROWN});
  ${COLORS_TAG.TAG_BG_ORANGE}: var(${COLORS_PRESET.ORANGE});
  ${COLORS_TAG.TAG_BG_YELLOW}: var(${COLORS_PRESET.YELLOW});
  ${COLORS_TAG.TAG_TYPE_CARD_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_TAG.TAG_TYPE_CARD_BACKGROUND}: var(${COLORS.BLACK_1});

  ${COLORS_GENERAL.BACKGROUND}: var(${COLORS.GRAY_11});
  ${COLORS_GENERAL.TEXT}: var(${COLORS_BRAND.GRAY});

  ${COLORS_TYPOGRAPHY.LINK}: var(${COLORS_BRAND.GRAY});

  ${COLORS_BUTTON.FOCUS_SHADOW}: var(${COLORS.GREEN_7});

  ${COLORS_BUTTON.FILLED_COLOR}: var(${COLORS_BRAND.BLACK});
  ${COLORS_BUTTON.FILLED_ICON_COLOR}: var(${COLORS_BRAND.BLACK});
  ${COLORS_BUTTON.FILLED_BG}: var(${COLORS.GREEN_3});
  ${COLORS_BUTTON.FILLED_HOVER_BG}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.FILLED_ACTIVE_BG}: var(${COLORS.GREEN_5});
  ${COLORS_BUTTON.FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_BUTTON.FILLED_DISABLED_BG}: var(${COLORS.GRAY_7});
  ${COLORS_BUTTON.FILLED_FOCUS_BG}: var(${COLORS.GREEN_4});

  ${COLORS_BUTTON.OUTLINED_COLOR}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.OUTLINED_BORDER}: var(${COLORS.GREEN_3});
  ${COLORS_BUTTON.OUTLINED_HOVER_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.OUTLINED_HOVER_BORDER}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.OUTLINED_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
  ${COLORS_BUTTON.OUTLINED_ACTIVE_BORDER}: var(${COLORS.GREEN_5});
  ${COLORS_BUTTON.OUTLINED_DISABLED_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_BUTTON.OUTLINED_DISABLED_BORDER}: var(${COLORS.GRAY_4});
  ${COLORS_BUTTON.OUTLINED_FOCUS_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.OUTLINED_FOCUS_BORDER}: var(${COLORS.GREEN_4});

  ${COLORS_BUTTON.TRANSPARENT_COLOR}: var(${COLORS.GREEN_3});
  ${COLORS_BUTTON.TRANSPARENT_HOVER_BG}: var(${COLORS.GRAY_7});
  ${COLORS_BUTTON.TRANSPARENT_HOVER_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.TRANSPARENT_ACTIVE_BG}: var(${COLORS.GRAY_7});
  ${COLORS_BUTTON.TRANSPARENT_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
  ${COLORS_BUTTON.TRANSPARENT_DISABLED_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_BUTTON.TRANSPARENT_FOCUS_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.TRANSPARENT_FOCUS_BG}: var(${COLORS.GRAY_5});
  ${COLORS_BUTTON.TRANSPARENT_FOCUS_BORDER}: transparent;

  ${COLORS_BUTTON.TABLE_MENU_BUTTON_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_BUTTON.TABLE_MENU_BUTTON_HOVER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.TABLE_MENU_BUTTON_DISABLED_COLOR}: #454545;
  ${COLORS_BUTTON.TABLE_MENU_BUTTON_ACTIVE_COLOR}: #a0a0a0;

  ${COLORS_BUTTON.FILLED_BRAND_COLOR}: #343f48;
  ${COLORS_BUTTON.FILLED_BRAND_BG}: #07e897;
  ${COLORS_BUTTON.FILLED_BRAND_HOVER_BG}: #07d88d;
  ${COLORS_BUTTON.FILLED_BRAND_ACTIVE_BG}: #07cc85;
  ${COLORS_BUTTON.FILLED_BRAND_DISABLED_COLOR}: #cfcfcf;
  ${COLORS_BUTTON.FILLED_BRAND_DISABLED_BG}: #ededed;
  ${COLORS_BUTTON.FILLED_BRAND_FOCUS_BG}: #07d88d;

  ${COLORS_BUTTON.WHITE_COLOR}: #282D30;
  ${COLORS_BUTTON.WHITE_BG}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.WHITE_HOVER_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.WHITE_HOVER_BG}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.WHITE_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
  ${COLORS_BUTTON.WHITE_ACTIVE_BG}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.WHITE_DISABLED_COLOR}: #63677380;
  ${COLORS_BUTTON.WHITE_DISABLED_BG}: #ffffff80;
  ${COLORS_BUTTON.WHITE_FOCUS_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_BUTTON.WHITE_FOCUS_BG}: var(${COLORS.WHITE});
  ${COLORS_BUTTON.WHITE_FOCUS_OUTLINE}: var(${COLORS.GREEN_7});
  ${COLORS_BUTTON.WHITE_FOCUS_BORDER}: transparent;

  ${COLORS_STATUS.COLOR}: var(${COLORS.GRAY_1});
  ${COLORS_STATUS.FAILED_BG}: var(${COLORS.RED_2});
  ${COLORS_STATUS.SUCCESS_BG}: var(${COLORS.GREEN_3});
  ${COLORS_STATUS.WARNING_BG}: var(${COLORS.YELLOW});
  ${COLORS_STATUS.UNACTIVE_BG}: var(${COLORS.GRAY_3});

  ${COLORS_SWITCH.UNACTIVE_BG}: var(${COLORS.GRAY_3});
  ${COLORS_SWITCH.UNACTIVE_HOVER_BG}: var(${COLORS.GRAY_4});
  ${COLORS_SWITCH.UNACTIVE_DISABLED_BG}: var(${COLORS.GRAY_5});
  ${COLORS_SWITCH.ACTIVE_BG}: var(${COLORS.GREEN_3});
  ${COLORS_SWITCH.ACTIVE_HOVER_BG}: var(${COLORS.GREEN_4});
  ${COLORS_SWITCH.ACTIVE_DISABLED_BG}: var(${COLORS.GREEN_7});

  ${COLORS_TOOLTIP.CONTAINER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TOOLTIP.CONTAINER_BG}: var(${COLORS_BRAND.BLACK});
  ${COLORS_TOOLTIP.ICON_FILL}: var(${COLORS_BRAND.GRAY});
  ${COLORS_TOOLTIP.ICON_HOVER_FILL}: var(${COLORS.WHITE});
  ${COLORS_TOOLTIP.MENU_BG}: var(${COLORS.GRAY_8});
  ${COLORS_TOOLTIP.MENU_ITEM_HOVER_BG}: var(${COLORS.GRAY_7});

  ${COLORS_FORM_GROUP.NUMBER_COLOR}: var(${COLORS_BRAND.BLACK});
  ${COLORS_FORM_GROUP.NUMBER_BG}: var(${COLORS.GREEN_3});
  ${COLORS_FORM_GROUP.HINT_COLOR}: var(${COLORS.GRAY_4});

  ${COLORS_FORM_FIELD.HINT_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_FORM_FIELD.ERROR_COLOR}: var(${COLORS.RED_1});

  ${COLORS_DRAWER.BACKGROUND}: var(${COLORS.GRAY_9});
  ${COLORS_DRAWER.BORDER_COLOR}: var(${COLORS.GRAY_5});

  ${COLORS_TOAST.INFO_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TOAST.INFO_BG}: var(${COLORS.GRAY_5});
  ${COLORS_TOAST.INFO_SECONDARY_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_TOAST.INFO_ICON_BG}: rgba(255, 255, 255, 0.1);
  ${COLORS_TOAST.INFO_ACTION_COLOR}: #cfcfcf;
  ${COLORS_TOAST.INFO_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TOAST.ERROR_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TOAST.ERROR_BG}: var(${COLORS.RED_1});
  ${COLORS_TOAST.ERROR_SECONDARY_COLOR}: #f5f5f5;
  ${COLORS_TOAST.ERROR_ICON_BG}: rgba(255, 255, 255, 0.1);
  ${COLORS_TOAST.ERROR_ACTION_COLOR}: #ededed;
  ${COLORS_TOAST.ERROR_ACTION_HOVER_COLOR}: var(${COLORS.WHITE});

  ${COLORS_RADIO.COLOR}: var(${COLORS.GRAY_1});
  ${COLORS_RADIO.SECONDARY_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_RADIO.DISABLED_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_RADIO.HOVER_BG}: var(${COLORS.GRAY_7});
  ${COLORS_RADIO.CHECKED_BG}: var(${COLORS.GRAY_8});
  ${COLORS_RADIO.ICON_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_RADIO.ICON_BG}: var(${COLORS.GRAY_9});
  ${COLORS_RADIO.ICON_HOVER_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_RADIO.ICON_DISABLED_COLOR}: var(${COLORS.GRAY_6});
  ${COLORS_RADIO.CHECKED_ICON_COLOR}: var(${COLORS.GREEN_3});
  ${COLORS_RADIO.CHECKED_ICON_HOVER_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_RADIO.CHECKED_ICON_DISABLED_COLOR}: var(${COLORS.GRAY_6});

  ${COLORS_SELECT.TEXT_COLOR}: var(${COLORS.WHITE});
  ${COLORS_SELECT.TEXT_OPTION_DISABLED_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_SELECT.GROUP_HEADING_TEXT_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_SELECT.PLACEHOLDER_TEXT_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_SELECT.BACKGROUND}: var(${COLORS.GRAY_8});
  ${COLORS_SELECT.BACKGROUND_HOVER}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.BACKGROUND_WITH_LOGO}: var(${COLORS.GRAY_8});
  ${COLORS_SELECT.BACKGROUND_WITH_LOGO_HOVER}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.BORDER_COLOR}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.BORDER_HOVER_COLOR}: var(${COLORS.GREEN_3});
  ${COLORS_SELECT.BORDER_FOCUS_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_SELECT.BORDER_ERROR_COLOR}: var(${COLORS.RED_1});
  ${COLORS_SELECT.DISABLED_BORDER_COLOR}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
  ${COLORS_SELECT.DROPDOWN_BACKGROUND}: var(${COLORS.GRAY_8});
  ${COLORS_SELECT.DROPDOWN_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
  ${COLORS_SELECT.DROPDOWN_FOCUS_BACKGROUND}: var(${COLORS.GRAY_6});
  ${COLORS_SELECT.DROPDOWN_ICON_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_SELECT.DROPDOWN_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

  ${COLORS_TOOLBAR.BACKGROUND}: var(${COLORS.GRAY_8});
  ${COLORS_TOOLBAR.INPUT_BORDER}: var(${COLORS.GRAY_11});
  ${COLORS_TOOLBAR.ACTIVE_BUTTON}: var(${COLORS.WHITE});
  ${COLORS_TOOLBAR.PLACEHOLDER_COLOR}: var(${COLORS.GRAY_2});

  ${COLORS_INPUT.INPUT_BG}: var(${COLORS.GRAY_8});
  ${COLORS_INPUT.INPUT_BORDER}: var(${COLORS.GRAY_7});
  ${COLORS_INPUT.INPUT_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_INPUT.INPUT_TEXT_COLOR}: var(${COLORS.WHITE});
  ${COLORS_INPUT.INPUT_FOCUS_BORDER}: var(${COLORS.GRAY_3});
  ${COLORS_INPUT.INPUT_FOCUS_BACKGROUND}: var(${COLORS.GRAY_7});
  ${COLORS_INPUT.INPUT_HOVER_BORDER}: var(${COLORS.GREEN_3});
  ${COLORS_INPUT.INPUT_HOVER_PLACEHOLDER_COLOR}: var(${COLORS.GRAY_1});
  ${COLORS_INPUT.INPUT_HOVER_BACKGROUND}: var(${COLORS.GRAY_7});
  ${COLORS_INPUT.INPUT_ERROR}: var(${COLORS.RED_1});
  ${COLORS_INPUT.INPUT_DISABLED_BACKGROUND}: var(${COLORS.BLACK_1});
  ${COLORS_INPUT.INPUT_DISABLED_COLOR}: var(${COLORS.GRAY_5});
  ${COLORS_INPUT.INPUT_DISABLED_BORDER}: var(${COLORS.GRAY_7});
  ${COLORS_INPUT.INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_INPUT.INPUT_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_INPUT.COPY_INPUT_BACKGROUND}: var(${COLORS.BLACK_1});
  ${COLORS_INPUT.COPY_INPUT_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_INPUT.COPY_INPUT_ICON_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_INPUT.COPY_INPUT_ICON_HOVER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_INPUT.COPY_INPUT_ICON_BACKGROUND_COLOR}: var(${COLORS.GRAY_8});

  ${COLORS_DIVIDER.COLOR_LIGHT}: var(${COLORS.GRAY_9});
  ${COLORS_DIVIDER.COLOR_MIDDLE}: var(${COLORS.GRAY_8});
  ${COLORS_DIVIDER.COLOR_DARK}: var(${COLORS.GRAY_5});

  ${COLORS_SPIN.BORDER}: var(${COLORS.WHITE});
  ${COLORS_SPIN.BORDER_TOP}: #ffffff33;
  ${COLORS_SPIN.TEXT_COLOR}: var(${COLORS.WHITE});
  ${COLORS_SPIN.BORDER_REV}: var(${COLORS.GRAY_3});
  ${COLORS_SPIN.BORDER_REV_TOP}: var(${COLORS.GRAY_1});
  ${COLORS_SPIN.TEXT_REV_COLOR}: var(${COLORS.BLACK_2});

  ${COLORS_MODAL.BG}: var(${COLORS.GRAY_8});
  ${COLORS_MODAL.TITLE_COLOR}: var(${COLORS.WHITE});
  ${COLORS_MODAL.DESCRIPTION_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_MODAL.PREVIEW_BG}: var(${COLORS.GRAY_8});
  ${COLORS_MODAL.PREVIEW_CLOSE_ICON_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_MODAL.PREVIEW_CLOSE_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

  ${COLORS_CHECKBOX.CHECKBOX_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_CHECKBOX.CHECKBOX_HOVER_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_CHECKBOX.CHECKBOX_DISABLED_COLOR}: var(${COLORS.GRAY_6});
  ${COLORS_CHECKBOX.CHECKBOX_DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_6});
  ${COLORS_CHECKBOX.CHECKBOX_FILLED_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_CHECKBOX.CHECKBOX_FILLED_HOVER_COLOR}: var(${COLORS.GREEN_4});
  ${COLORS_CHECKBOX.CHECKBOX_FILLED_DISABLED_COLOR}: var(${COLORS.GRAY_6});

  ${COLORS_BREADCRUMBS.ACTIVE_COLOR}: var(${COLORS.WHITE});
  ${COLORS_BREADCRUMBS.INACTIVE_COLOR}: var(${COLORS.GRAY_2});

  ${COLORS_AVATAR.COLOR}: var(${COLORS.BLACK_2});
  ${COLORS_AVATAR.BG}: var(${COLORS.GRAY_3});
  ${COLORS_AVATAR.TEXT_COLOR}: var(${COLORS.WHITE});
  ${COLORS_AVATAR.BG_GREEN}: var(${COLORS_PRESET.GREEN});
  ${COLORS_AVATAR.BG_BLUE}: var(${COLORS_PRESET.BLUE});
  ${COLORS_AVATAR.BG_PURPLE}: var(${COLORS_PRESET.PURPLE});
  ${COLORS_AVATAR.BG_PINK}: var(${COLORS_PRESET.PINK});
  ${COLORS_AVATAR.BG_RED}: var(${COLORS_PRESET.RED});
  ${COLORS_AVATAR.BG_GRAY_DEFAULT}: var(${COLORS_PRESET.GRAY_DEFAULT});
  ${COLORS_AVATAR.BG_GRAY}: var(${COLORS_PRESET.GRAY});
  ${COLORS_AVATAR.BG_BROWN}: var(${COLORS_PRESET.BROWN});
  ${COLORS_AVATAR.BG_ORANGE}: var(${COLORS_PRESET.ORANGE});
  ${COLORS_AVATAR.BG_YELLOW}: var(${COLORS_PRESET.YELLOW});

  ${COLORS_SLIDER.BG}: var(${COLORS.GREEN_3});
  ${COLORS_SLIDER.BG_HOVER}: var(${COLORS.GREEN_4});
  ${COLORS_SLIDER.BG_ACTIVE}: var(${COLORS.GREEN_5});
  ${COLORS_SLIDER.INACTIVE_BG}: var(${COLORS.GRAY_3});

  ${COLORS_ICON_BUTTON.BLUE_COLOR}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.BLUE_BORDER_COLOR}: var(${COLORS.GREEN_3});
  ${COLORS_ICON_BUTTON.BLUE_COLOR_HOVER}: var(${COLORS.GREEN_4});
  ${COLORS_ICON_BUTTON.BLUE_BORDER_COLOR_HOVER}: var(${COLORS.GREEN_4});
  ${COLORS_ICON_BUTTON.BLUE_COLOR_ACTIVE}: var(${COLORS.GREEN_5});
  ${COLORS_ICON_BUTTON.BLUE_BORDER_COLOR_ACTIVE}: var(${COLORS.GREEN_5});
  ${COLORS_ICON_BUTTON.BLUE_COLOR_DISABLED}: var(${COLORS.GRAY_4});
  ${COLORS_ICON_BUTTON.BLUE_BORDER_COLOR_DISABLED}: var(${COLORS.GRAY_4});
  ${COLORS_ICON_BUTTON.BLUE_COLOR_FOCUS}: var(${COLORS.GREEN_6});
  ${COLORS_ICON_BUTTON.BLUE_BORDER_COLOR_FOCUS}: var(${COLORS.GREEN_4});
  ${COLORS_ICON_BUTTON.BLUE_FOCUS_SHADOW}: var(${COLORS.GREEN_7});

  ${COLORS_ICON_BUTTON.WHITE_COLOR}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.WHITE_BORDER_COLOR}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.WHITE_COMMON_BG}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.WHITE_COLOR_HOVER}: var(${COLORS.GREEN_3});
  ${COLORS_ICON_BUTTON.WHITE_BORDER_COLOR_HOVER}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.WHITE_COLOR_ACTIVE}: var(${COLORS.GREEN_3});
  ${COLORS_ICON_BUTTON.WHITE_BORDER_COLOR_ACTIVE}: var(${COLORS.WHITE});
  ${COLORS_ICON_BUTTON.WHITE_COLOR_DISABLED}: var(${COLORS.GREEN_1});
  ${COLORS_ICON_BUTTON.WHITE_BORDER_COLOR_DISABLED}: var(${COLORS.GREEN_1});
  ${COLORS_ICON_BUTTON.WHITE_COLOR_FOCUS}: var(${COLORS.GREEN_3});
  ${COLORS_ICON_BUTTON.WHITE_BORDER_COLOR_FOCUS}: transparent;
  ${COLORS_ICON_BUTTON.WHITE_FOCUS_SHADOW}: var(${COLORS.GREEN_7});

  ${COLORS_ICON_BUTTON.HEADER_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_ICON_BUTTON.HEADER_COLOR_HOVER}: var(${COLORS.WHITE});

  ${COLORS_ICON_BUTTON.HEADER_MENU_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_ICON_BUTTON.HEADER_MENU_COLOR_HOVER}: var(${COLORS.WHITE});

  ${COLORS_ICON_BUTTON.SIDEBAR_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_ICON_BUTTON.SIDEBAR_COLOR_HOVER}: var(${COLORS.WHITE});

  ${COLORS_LOGS_VIEW.BG}: var(${COLORS.GRAY_10});

  ${COLORS_TABLE.TABLE_BORDER}: var(${COLORS.GRAY_2});
  ${COLORS_TABLE.TABLE_ROW_COLOR}: var(${COLORS.WHITE});
  ${COLORS_TABLE.TABLE_ROW_BACKGROUND}: var(${COLORS.GRAY_8});
  ${COLORS_TABLE.TABLE_ROW_ODD_BACKGROUND}: var(${COLORS.GRAY_7});
  ${COLORS_TABLE.TABLE_ROW_HOVER_SHADOW_LEFT}: var(${COLORS.GREEN_3});
  ${COLORS_TABLE.TABLE_ROW_HOVER_SHADOW_TOP_BOTTOM}: #717171;
  ${COLORS_TABLE.TABLE_ROW_SELECTED_BACKGROUND}: var(${COLORS.GRAY_9});
  ${COLORS_TABLE.TABLE_HEADER_BACKGROUND}: var(${COLORS.GRAY_7});
  ${COLORS_TABLE.TABLE_HEADER_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_TABLE.TABLE_HEADER_RESIZE_ICON_COLOR}: var(${COLORS.GRAY_3});
  ${COLORS_TABLE.TABLE_FAVOURITE_ICON_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_TABLE.TABLE_FAVOURITE_ICON_HOVER_COLOR}: var(${COLORS.GRAY_4});
  ${COLORS_TABLE.TABLE_FAVOURITE_ICON_FILLED_COLOR}: var(${COLORS.YELLOW});
  ${COLORS_TABLE.TABLE_RADIO_ICON_DISABLED_COLOR}: var(${COLORS.GRAY_5});
  ${COLORS_TABLE.TABLE_HELP_ICON_COLOR}: var(${COLORS_BRAND.GRAY});
  ${COLORS_TABLE.TABLE_HELP_ICON_HOVER_COLOR}: var(${COLORS.WHITE});

  ${COLORS_PAGINATE.PAGINATE_ACTIVE_COLOR}: var(${COLORS.GREEN_5});
  ${COLORS_PAGINATE.PAGINATE_DISABLED_COLOR}: var(${COLORS.GRAY_7});
  ${COLORS_PAGINATE.PAGINATE_WHITE_COLOR}: var(${COLORS.WHITE});

  ${COLORS_ATTENTION.NORMAL_IMPORTANCE_LEVEL_LINE}: var(${COLORS.GREEN_5});
  ${COLORS_ATTENTION.HIGH_IMPORTANCE_LEVEL_LINE}: var(${COLORS.RED_1});

  ${COLORS_HIERARCHY_MENU.MENU_BACKGROUND}: var(${COLORS.BLACK_1});
  ${COLORS_HIERARCHY_MENU.ACCORDION_NODE_ICON}: var(${COLORS.WHITE});
  ${COLORS_HIERARCHY_MENU.ACCORDION_NODE_TEXT}: var(${COLORS.GRAY_1});
  ${COLORS_HIERARCHY_MENU.ACCORDION_NODE_HOVER_TEXT}: var(${COLORS.WHITE});
  ${COLORS_HIERARCHY_MENU.ACCORDION_NODE_ACTIVE_TEXT}: var(${COLORS.VIOLET_4});
  ${COLORS_HIERARCHY_MENU.LEAF_NODE_ICON}: var(${COLORS.GRAY_3});
  ${COLORS_HIERARCHY_MENU.LEAF_NODE_TEXT}: var(${COLORS.GRAY_1});
  ${COLORS_HIERARCHY_MENU.LEAF_NODE_ACTIVE}: var(${COLORS.VIOLET_4});
  ${COLORS_HIERARCHY_MENU.LEAF_NODE_HOVER}: var(${COLORS.WHITE});

  ${COLORS_TABS.TAB_ACTIVE_COLOR}: var(${COLORS.GREEN_3});
  ${COLORS_TABS.TAB_BORDER_COLOR}: #ededed;
  ${COLORS_TABS.TAB_GRAY_BORDER_COLOR}: #d2d2d2;
  ${COLORS_TABS.TAB_TEXT_COLOR}: var(${COLORS.GRAY_2});
  ${COLORS_TABS.TAB_DISABLED_TEXT_COLOR}: var(${COLORS.GRAY_5});
`;
