export const TEST_IDS = {
  main: 'toolbar',
  checkbox: 'toolbar__checkbox',
  confirmAction: 'toolbar__confirm-action',
  rejectAction: 'toolbar__reject-action',
  deleteAction: 'toolbar__delete-action',
  deactivateAction: 'toolbar__deactivate-action',
  disabledAction: 'toolbar__disabled-action',
  bulkActions: 'toolbar__bulk-actions',
  moreBulkActionsButton: 'toolbar__more-bulk-actions-button',
  refreshButton: 'toolbar__refresh-button',
  search: 'toolbar__search',
  moreActionsButton: 'toolbar__more-actions-button',
  droplist: 'toolbar__droplist',
  option: 'toolbar__droplist-option',
  after: 'toolbar__after',
};
