#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node_modules/.bin/lint-staged
node_modules/.bin/ts-node scripts/check-dependencies.ts
node_modules/.bin/ts-node scripts/docgen/docgenForStagedPackages.ts
